name: 'Build and Publish Docker'
description: 'Builds and publishes Docker images to Docker Hub'
inputs:
  image_name:
    description: 'Docker image name'
    required: true
  image_tag:
    description: 'Docker image tag'
    default: 'latest'
  dockerhub_username:
    description: 'Docker Hub username'
    required: true
  dockerhub_token:
    description: 'Docker Hub token'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}
    - name: Build and push Docker image - Latest
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jidotaikasuru/${{ inputs.image_name }}:${{ inputs.image_tag }}
  # TODO Deploy to EC2 instances here
