# .github/actions/publish-docker.yml
name: 'Build and Publish Docker'
description: 'Builds and publishes Docker images to Docker Hub'
inputs:
  image_name:
    description: 'Docker image name'
    required: true
  image_tag:
    description: 'Docker image tag'
    default: 'latest'

runs:
  using: 'composite'
jobs:
  build:
    env:
      IMAGE_NAME: your-image-name  # Define your variable here
    strategy:
      matrix:
        tag: ["latest", "${{ github.sha }}"]
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker image - Latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}
    # TODO Deploy to EC2 instances here
